PACKAGE          = MissingETUtility
PACKAGE_CXXFLAGS = -DMETUTIL_STANDALONE
PACKAGE_LDFLAGS  = 
PACKAGE_DEP      = JetUncertainties JetResolution MuonMomentumCorrections egammaAnalysisUtils

include $(ROOTCOREDIR)/Makefile-common

