Job (
 inputdata = CRABDataset (
    inputdata = '####DATASETPATH####',
    pset = '####PSET####',
    workflow = '####WORKFLOW####',
    cacheurl = 'https://cmsweb.cern.ch/crabcache/file',
    cachefilename = '6a784255e1ea281f32d83120dd8289264c7e8f2743455d9f359fd17f69252073.tar.gz',
    publishname = '0ea12bcd230936c2556840cb8452714d',
    savelogsflag = 0,
    nonprodsw = 0,
    tfileoutfiles = [],
    asyncdest = 'T2_CH_CERN',
    oneEventMode = 0,
    algoargs = 100,
    totalunits = 1000,
    jobarch = 'slc5_amd64_gcc462',
    publication = 0,
    splitalgo = 'EventBased',
    jobsw = '####CMSSW####',
    dbsurl = 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader',
    addoutputfiles = [],
    edmoutfiles = ['step1.root'],
    adduserfiles = [],
    jobtype = 'PrivateMC',
    siteblacklist = [],
    sitewhitelist = ['####SITEWHITELIST####'],
    ) ,
 application = CRABApp () ,
 backend = CRABBackend (),
)
