# Author: Karsten Koeneke (karsten.koeneke@cernSPAMNOT.ch)
# JetSelectorTools root stand-alone makefile

PACKAGE          = JetSelectorTools
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  =
PACKAGE_DEP      = ObjectSelectorCore

include $(ROOTCOREDIR)/Makefile-common
