PACKAGE          = SUSYTools
PACKAGE_CXXFLAGS =
PACKAGE_LDFLAGS  = $(shell root-config --libs) -lPyROOT -lXMLParser -lEG
PACKAGE_DEP      = MuonMomentumCorrections MuonEfficiencyCorrections egammaEvent egammaAnalysisUtils JetSelectorTools CalibrationDataInterface GoodRunsLists PileupReweighting PileupReweighting JetResolution JetUncertainties MissingETUtility ReweightUtils 

include $(ROOTCOREDIR)/Makefile-common
