# Author: Max Baak (mbaak@cern.ch)
# GoodRunsLists root stand-alone makefile

PACKAGE          = GoodRunsLists
PACKAGE_PRELOAD  = Tree TreePlayer XMLParser XMLIO
PACKAGE_CXXFLAGS = -I/usr/include/libxml2
PACKAGE_BINFLAGS = -lxml2
#PACKAGE_LDFLAGS  = -lxml2 -L$(ROOTSYS)/lib/root -L$(ROOTSYS)/lib -lXMLIO -lXMLParser -lz

include $(ROOTCOREDIR)/Makefile-common
